name: Check types
on:
  workflow_call:
env:
  NODE_OPTIONS: --max-old-space-size=4096
permissions:
  contents: read
  packages: read
jobs:
  get-image:
    name: Get Docker Image
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      image: ${{ steps.get-image.outputs.full-image }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Check if yarn.lock changed and if image exists
        id: check-build-needed
        run: |
          YARN_LOCK_HASH=$(sha256sum yarn.lock | cut -d' ' -f1 | cut -c1-12)
          PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")
          # Sanitize version string for Docker tag (remove ^, ~, and other invalid characters)
          PLAYWRIGHT_VERSION_CLEAN=$(echo "$PLAYWRIGHT_VERSION" | sed 's/[^a-zA-Z0-9.-]//g')
          IMAGE_TAG="yarn-${YARN_LOCK_HASH}-playwright-${PLAYWRIGHT_VERSION_CLEAN}"
          FULL_IMAGE="ghcr.io/calcom/cal.com-deps:${IMAGE_TAG}"

          # Log in to GitHub Container Registry to check if image exists
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Check if yarn.lock changed
          if git diff --name-only origin/main...HEAD | grep -q "yarn.lock"; then
            echo "yarn-lock-changed=true" >> $GITHUB_OUTPUT
            echo "yarn.lock has changed, will build new image"
            echo "build-needed=true" >> $GITHUB_OUTPUT
          else
            echo "yarn-lock-changed=false" >> $GITHUB_OUTPUT
            echo "yarn.lock unchanged, checking if image exists"

            # Check if image exists in registry
            if docker manifest inspect ${FULL_IMAGE} > /dev/null 2>&1; then
              echo "Image exists in registry, no build needed"
              echo "build-needed=false" >> $GITHUB_OUTPUT
            else
              echo "Image does not exist in registry, will build"
              echo "build-needed=true" >> $GITHUB_OUTPUT
            fi
          fi

          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "full-image=${FULL_IMAGE}" >> $GITHUB_OUTPUT

  check-types:
    needs: get-image
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: ${{ needs.get-image.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --workdir /workspace
    steps:
      - name: Debug container environment
        run: |
          echo "=== Container Environment Debug ==="
          echo "Current working directory: $(pwd)"
          echo "Home directory: $HOME"
          echo "User: $(whoami)"
          echo "Container hostname: $(hostname)"
          echo "Available disk space:"
          df -h
          echo "Directory contents:"
          ls -la /
          echo "Workspace directory contents:"
          ls -la /workspace || echo "No /workspace directory found"
          echo "Node modules check:"
          ls -la /workspace/node_modules || echo "No node_modules in /workspace"
          echo "Yarn state file check:"
          find /workspace -name ".pnp.*" -o -name "yarn.lock" -o -name ".yarn" 2>/dev/null || echo "No yarn files found"
          echo "=== End Debug ==="
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Show info
        run: node -e "console.log(require('v8').getHeapStatistics())"
      - name: Configure TSC problem matcher
        run: |
          echo "::remove-matcher owner=tsc::"
          echo "::add-matcher::.github/matchers/tsc-absolute.json"
      - run: yarn type-check:ci
