name: Lint
on:
  workflow_call:
permissions:
  actions: write
  contents: read
  packages: read
jobs:
  get-image:
    name: Get Docker Image
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      image: ${{ steps.get-image.outputs.full-image }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Get image tag
        id: get-image
        uses: ./.github/actions/use-deps-image

  lint:
    needs: get-image
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: ${{ needs.get-image.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --workdir /workspace
    steps:
      - name: Debug container environment
        run: |
          echo "=== Container Environment Debug ==="
          echo "Current working directory: $(pwd)"
          echo "Home directory: $HOME"
          echo "User: $(whoami)"
          echo "Container hostname: $(hostname)"
          echo "Available disk space:"
          df -h
          echo "Directory contents:"
          ls -la /
          echo "Workspace directory contents:"
          ls -la /workspace || echo "No /workspace directory found"
          echo "Node modules check:"
          ls -la /workspace/node_modules || echo "No node_modules in /workspace"
          echo "Yarn state file check:"
          find /workspace -name ".pnp.*" -o -name "yarn.lock" -o -name ".yarn" 2>/dev/null || echo "No yarn files found"
          echo "=== End Debug ==="
      - uses: actions/checkout@v4
        with:
          path: /workspace
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Run Lint
        run: yarn lint
        continue-on-error: true
