name: Unit
on:
  workflow_call:
env:
  LINGO_DOT_DEV_API_KEY: ${{ secrets.CI_LINGO_DOT_DEV_API_KEY }}
permissions:
  contents: read
  packages: read
jobs:
  get-image:
    name: Get Docker Image
    runs-on: buildjet-2vcpu-ubuntu-2204
    outputs:
      image: ${{ steps.get-image.outputs.full-image }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - name: Get image tag
        id: get-image
        uses: ./.github/actions/use-deps-image

  test:
    name: Unit
    timeout-minutes: 20
    needs: get-image
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: ${{ needs.get-image.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --workdir /workspace
    steps:
      - name: Debug container environment
        run: |
          echo "=== Container Environment Debug ==="
          echo "Current working directory: $(pwd)"
          echo "Home directory: $HOME"
          echo "User: $(whoami)"
          echo "Container hostname: $(hostname)"
          echo "Available disk space:"
          df -h
          echo "Directory contents:"
          ls -la /
          echo "Workspace directory contents:"
          ls -la /workspace || echo "No /workspace directory found"
          echo "Node modules check:"
          ls -la /workspace/node_modules || echo "No node_modules in /workspace"
          echo "Yarn state file check:"
          find /workspace -name ".pnp.*" -o -name "yarn.lock" -o -name ".yarn" 2>/dev/null || echo "No yarn files found"
          echo "=== End Debug ==="
      - uses: actions/checkout@v4
        with:
          path: /workspace
      - uses: ./.github/actions/dangerous-git-checkout
      - run: yarn test -- --no-isolate
      # We could add different timezones here that we need to run our tests in
      - run: TZ=America/Los_Angeles yarn test -- --timeZoneDependentTestsOnly --no-isolate
      - name: Run API v2 tests
        working-directory: apps/api/v2
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn workspace @calcom/platform-libraries build && yarn test
